name: AuctionHouse
version: '1.3.8'
main: me.elaineqheart.auctionHouse.AuctionHouse
api-version: '1.21'
authors: [ ElaineQheart ]
website: https://www.youtube.com/@elaineqheart
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]
commands:
  ah:
    description: opens the auction house GUI
    permission: AuctionHouse.ah
    aliases:
      - auctionhouse
permissions:
  AuctionHouse.ah:
    description: allows the player to use /ah
    default: true

